#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright Red Hat
#

from pbit_lsb_release import lsb_command

#############################################################################
#############################################################################
if __name__ == "__main__":
  lsb_command()
